# Dependencies

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# highlighter: rouge
# highlighter:      pygments

# Permalinks
# permalink:        pretty

# Setup
title:            Chia-Hsun's Blog 
tagline:          'A Jekyll theme'
description:      'Website under construction'
url:              http://chiahsun.github.io
baseurl:          /

author:
  name:           'Chiahsun'
  url:            http://chiahsun.github.io

paginate:         5

# Custom vars
version:          0.0.1 beta

github:           chiahsun
repo:             chiahsun.github.io

# Gems
gems: [jekyll-paginate]

exclude:
    - ignore
    - code cookbook/src
    - algorithm cookbook/src
    - language cookbook/src 
