# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Chia-Hsun's Blog 
tagline:          'A Jekyll theme'
description:      'Website test'
url:              http://chiahsun.github.io
baseurl:          /

author:
  name:           'Chiahsun'
  url:            http://chiahsun.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:           chiahsun
repo:             chiahsun.github.io